### ISSUE TITLE
Crash while trying to integrate the Android RN SDK

### ISSUE THREAD

**Issue by avishayil** [BranchMetrics/DEPRECATED-React-Native-SDK#1]
App builds fine, but when running, encountering this error:
![screenshot_2016-03-15-22-17-35](https://cloud.githubusercontent.com/assets/827024/13792977/3688e388-eafd-11e5-9837-b7be3ef567b5.png)
Any ideas?

**Comment by rt2zz** [comment]
It looks like you may have included RNBranch twice in you MainActivity

**Comment by aaustin** [comment]
This repo is deprecated. Please try our new, more complete version here: https://github.com/BranchMetrics/React-Native-Deferred-Deep-Linking-SDK
