### ISSUE TITLE
Duplicate Symbols Pods-dummy.o

### ISSUE THREAD

**Issue by ewdicus** [BranchMetrics/DEPRECATED-React-Native-SDK#10]
Hello,

I have a project that's already using CocoaPods that I'm trying to use this library in. I seem to be getting duplicate symbols because the project already links against libPods.a

```
duplicate symbol _OBJC_CLASS_$_PodsDummy_Pods in:
    <...>/Build/Products/Debug-iphonesimulator/libRNBranch.a(Pods-dummy.o)
    <...>/Build/Products/Debug-iphonesimulator/libPods.a(Pods-dummy.o)
duplicate symbol _OBJC_METACLASS_$_PodsDummy_Pods in:
    <...>/Build/Products/Debug-iphonesimulator/libRNBranch.a(Pods-dummy.o)
    <...>/Build/Products/Debug-iphonesimulator/libPods.a(Pods-dummy.o)
ld: 2 duplicate symbols for architecture x86_64
```

What's the correct way to handle this? Thanks!

**Comment by rt2zz** [comment]
@ewdicus did you pod install inside of node_modules/branch-react-native-sdk *and* in your project root? Currently you can do either but not both.

We are working on a better installation method, I will keep you posted.

**Comment by ewdicus** [comment]
I'm not sure I understand. If I don't do the pod install inside node_modules/branch-react-native-sdk then there's no `/node_modules/react-native-branch/Pods/Pods.xcodeproj` to drag in to complete the installation. And if I can't do it in my project then I can't install new pods. Am I missing something?

Thanks again.

**Comment by ewdicus** [comment]
It looks like the fix here is to specify the target in the podfile. If you change the Podfile to:

```
platform :ios, '7.1'

xcodeproj 'RNBranch/RNBranch.xcodeproj'

target “RNBranch” do
    pod 'Branch'
end
```

And then run pod install in `../node_modules/branch-react-native-sdk/` this generates a `Pods-RNBranch-dummy.m` which prevents the duplicate symbols.

You can see some discussion about that here: http://stackoverflow.com/a/23370841

**Comment by aaustin** [comment]
This repo is deprecated. Please try our new, more complete version here: https://github.com/BranchMetrics/React-Native-Deferred-Deep-Linking-SDK
